const json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json","cache-control":"no-store",...h}});
const enc=new TextEncoder();
async function hmac(secret,data){return crypto.subtle.sign("HMAC",{name:"HMAC",hash:"SHA-256"},await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]),enc.encode(data))}
function hex(buf){return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function sameHmac(secret,data,sig){return hex(await hmac(secret,data))===sig}
async function razor(env,path,opts={}){const token=btoa(`${env.RAZORPAY_KEY_ID}:${env.RAZORPAY_KEY_SECRET}`);const r=await fetch(`https://api.razorpay.com/v1${path}`,{...opts,headers:{Authorization:`Basic ${token}`,"content-type":"application/json",...(opts.headers||{})}});const d=await r.json();if(!r.ok)throw Error(d.error?.description||"Razorpay API error");return d}
function license(){return `EDITH-${crypto.randomUUID().replaceAll("-","").slice(0,24).toUpperCase()}`}
async function admin(req,env){return req.headers.get("x-admin-token")===env.ADMIN_TOKEN}
function getCookie(req,name){const c=req.headers.get("cookie")||"";for(const part of c.split(";")){const [k,...v]=part.trim().split("=");if(k===name)return decodeURIComponent(v.join("="))}return null}
function sessionCookie(token){return `edith_session=${token}; Path=/; Max-Age=31536000; SameSite=Lax; Secure; HttpOnly`}
async function currentUser(req,env){const t=getCookie(req,"edith_session");if(!t)return null;return await env.DB.prepare("SELECT id,email,phone,name FROM users WHERE token=?").bind(t).first()}
async function notifyAdmin(env,text){if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_CHAT_ID)return;try{await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:env.TELEGRAM_CHAT_ID,text})})}catch(e){}}
async function routes(req,env){const u=new URL(req.url),p=u.pathname;
 if(p==="/api/auth/login"&&req.method==="POST"){const b=await req.json().catch(()=>({}));const email=String(b.email||"").trim().toLowerCase(),name=String(b.name||"").trim(),phone=String(b.phone||"").trim();if(!email||!email.includes("@")||!name)return json({error:"Naam aur email zaroori hai"},400);let rec=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(rec){await env.DB.prepare("UPDATE users SET name=?,phone=? WHERE id=?").bind(name,phone||rec.phone,rec.id).run()}else{const id=crypto.randomUUID(),token=crypto.randomUUID()+crypto.randomUUID();await env.DB.prepare("INSERT INTO users(id,email,phone,name,token,created_at) VALUES(?,?,?,?,?,?)").bind(id,email,phone,name,token,new Date().toISOString()).run();rec={token}}return json({ok:true,user:{name,email,phone}},200,{"set-cookie":sessionCookie(rec.token)})}
 if(p==="/api/auth/me"){const cu=await currentUser(req,env);return json({user:cu||null})}
 if(p==="/api/auth/logout"&&req.method==="POST"){return json({ok:true},200,{"set-cookie":"edith_session=; Path=/; Max-Age=0"})}
 if(p==="/api/plans"){const {results}=await env.DB.prepare("SELECT * FROM plans WHERE active=1 ORDER BY amount").all();return json({plans:results.map(x=>({...x,features:JSON.parse(x.features_json)}))})}
 if(p==="/api/releases/latest"){const r=await env.DB.prepare("SELECT version,version_code,price,notes,file_name,published_at FROM releases WHERE status='live' ORDER BY published_at DESC LIMIT 1").first();return json({release:r||null})}
 if(p==="/api/orders"&&req.method==="POST"){const b=await req.json();const plan=await env.DB.prepare("SELECT * FROM plans WHERE id=? AND active=1").bind(b.plan).first();const phone=String(b.phone||"").trim();if(!plan||!b.email||!b.email.includes("@")||!phone)return json({error:"Plan, email aur phone number zaroori hai"},400);const id=crypto.randomUUID();const ro=await razor(env,"/orders",{method:"POST",body:JSON.stringify({amount:plan.amount*100,currency:"INR",receipt:id,capture:"automatic",notes:{local_order_id:id,plan_id:plan.id,phone}})});await env.DB.prepare("INSERT INTO orders(id,plan_id,email,phone,amount,razorpay_order_id,status,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(id,plan.id,b.email,phone,plan.amount,ro.id,"created",new Date().toISOString()).run();await notifyAdmin(env,`🛒 New order started\nPlan: ${plan.name}\nEmail: ${b.email}\nPhone: ${phone}\nAmount: ₹${plan.amount}`);return json({key_id:env.RAZORPAY_KEY_ID,order_id:ro.id,amount:plan.amount*100,description:plan.name})}
 if(p==="/api/payment/verify"&&req.method==="POST"){const b=await req.json();const o=await env.DB.prepare("SELECT * FROM orders WHERE razorpay_order_id=?").bind(b.razorpay_order_id).first();if(!o)return json({error:"Order not found"},404);if(!(await sameHmac(env.RAZORPAY_KEY_SECRET,`${b.razorpay_order_id}|${b.razorpay_payment_id}`,b.razorpay_signature)))return json({error:"Signature verification failed"},400);const key=o.license_key||license();await env.DB.prepare("UPDATE orders SET status='paid',razorpay_payment_id=?,license_key=?,paid_at=? WHERE id=?").bind(b.razorpay_payment_id,key,new Date().toISOString(),o.id).run();await notifyAdmin(env,`✅ Payment confirmed\nEmail: ${o.email}\nPhone: ${o.phone||"—"}\nAmount: ₹${o.amount}\nLicense: ${key}`);return json({ok:true,license_key:key})}
 if(p==="/api/webhooks/razorpay"&&req.method==="POST"){const raw=await req.text(),sig=req.headers.get("x-razorpay-signature")||"";if(!env.RAZORPAY_WEBHOOK_SECRET||!(await sameHmac(env.RAZORPAY_WEBHOOK_SECRET,raw,sig)))return new Response("bad signature",{status:400});const ev=JSON.parse(raw),eid=ev.id||crypto.randomUUID();if(await env.DB.prepare("SELECT id FROM webhook_events WHERE id=?").bind(eid).first())return new Response("ok");await env.DB.prepare("INSERT INTO webhook_events(id,created_at) VALUES(?,?)").bind(eid,Date.now()).run();if(["payment.captured","order.paid"].includes(ev.event)){const payment=ev.payload?.payment?.entity,oid=payment?.order_id||ev.payload?.order?.entity?.id;if(oid){const o=await env.DB.prepare("SELECT * FROM orders WHERE razorpay_order_id=?").bind(oid).first();if(o&&o.status!=="paid")await env.DB.prepare("UPDATE orders SET status='paid',razorpay_payment_id=?,license_key=?,paid_at=? WHERE id=?").bind(payment?.id||null,license(),new Date().toISOString(),o.id).run()}}return new Response("ok")}
 if(p==="/api/admin/releases"&&req.method==="GET"){if(!(await admin(req,env)))return json({error:"Unauthorized"},401);const {results}=await env.DB.prepare("SELECT * FROM releases ORDER BY published_at DESC LIMIT 50").all();return json({releases:results})}
 if(p==="/api/admin/releases"&&req.method==="POST"){if(!(await admin(req,env)))return json({error:"Unauthorized"},401);const body=await req.json().catch(()=>({}));const apkUrl=String(body.apk_url||"").trim(),version=String(body.version||"").trim(),notes=String(body.notes||"").trim(),price=Number(body.price||59),fileName=String(body.file_name||`edith-${version}.apk`);if(!apkUrl||!version)return json({error:"Version and APK URL are required"},400);const code=Date.now();await env.DB.prepare("UPDATE releases SET status='archived' WHERE status='live'").run();const id=crypto.randomUUID();await env.DB.prepare("INSERT INTO releases(id,version,version_code,price,notes,file_key,file_name,file_size,status,published_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,version,code,price,notes,apkUrl,fileName,0,"live",new Date().toISOString()).run();return json({ok:true,id})}
 if(p.startsWith("/api/download/latest")){const key=u.searchParams.get("license");if(!key)return json({error:"License required"},401);const o=await env.DB.prepare("SELECT * FROM orders WHERE license_key=? AND status='paid' LIMIT 1").bind(key).first();if(!o)return json({error:"Invalid license"},403);const r=await env.DB.prepare("SELECT * FROM releases WHERE status='live' ORDER BY published_at DESC LIMIT 1").first();if(!r)return json({error:"No release published"},404);return Response.redirect(r.file_key,302)}
 if(p==="/api/admin/orders"&&req.method==="GET"){if(!(await admin(req,env)))return json({error:"Unauthorized"},401);const {results}=await env.DB.prepare("SELECT * FROM orders ORDER BY created_at DESC LIMIT 100").all();return json({orders:results})}
 return null}
export default {async fetch(req,env){try{const r=await routes(req,env);return r||env.ASSETS.fetch(req)}catch(e){return json({error:e.message||"Server error"},500)}}};
